"""initial_baseline

Revision ID: 4438d492c1c6
Revises: 
Create Date: 2026-09-15 09:45:15.319412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4438d492c1c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Normalizar datos preexistentes con valores por defecto antes de aplicar restricciones NOT NULL
    op.execute("UPDATE medicos SET horario_atencion = '{}' WHERE horario_atencion IS NULL")
    op.execute("UPDATE consultas_medicas SET estudios_solicitados = '[]' WHERE estudios_solicitados IS NULL")
    op.execute("UPDATE consultas_medicas SET reposo_medico = '{}' WHERE reposo_medico IS NULL")
    op.execute("UPDATE citas_medicas SET estado_pago = 'pendiente' WHERE estado_pago IS NULL")
    op.execute("UPDATE citas_medicas SET es_sobreturno = 0 WHERE es_sobreturno IS NULL")
    op.execute("UPDATE citas_medicas SET recordatorio_enviado = 0 WHERE recordatorio_enviado IS NULL")
    op.execute("UPDATE empresas SET moneda_principal = 'USD' WHERE moneda_principal IS NULL")

    op.alter_column('citas_medicas', 'estado_pago',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               nullable=False,
               existing_server_default=sa.text("'pendiente'"))
    op.alter_column('citas_medicas', 'es_sobreturno',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('citas_medicas', 'recordatorio_enviado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_citas_medicas_estado_pago'), 'citas_medicas', ['estado_pago'], unique=False)
    op.create_index(op.f('ix_citas_medicas_servicio_id'), 'citas_medicas', ['servicio_id'], unique=False)
    op.create_foreign_key('fk_citas_medicas_servicio_id', 'citas_medicas', 'servicios', ['servicio_id'], ['id'], ondelete='SET NULL')
    op.alter_column('consultas_medicas', 'estudios_solicitados',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('consultas_medicas', 'reposo_medico',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index(op.f('codigo'), table_name='consultas_medicas')
    op.create_index(op.f('ix_consultas_medicas_cita_id'), 'consultas_medicas', ['cita_id'], unique=False)
    op.create_index(op.f('ix_consultas_medicas_codigo'), 'consultas_medicas', ['codigo'], unique=True)
    op.create_index(op.f('ix_consultas_medicas_creado_por'), 'consultas_medicas', ['creado_por'], unique=False)
    op.create_index(op.f('ix_consultas_medicas_estado'), 'consultas_medicas', ['estado'], unique=False)
    op.create_index(op.f('ix_consultas_medicas_preconsulta_id'), 'consultas_medicas', ['preconsulta_id'], unique=False)
    op.create_foreign_key('fk_consultas_medicas_creado_por', 'consultas_medicas', 'usuarios', ['creado_por'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_consultas_medicas_preconsulta_id', 'consultas_medicas', 'preconsultas', ['preconsulta_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_consultas_medicas_cita_id', 'consultas_medicas', 'citas_medicas', ['cita_id'], ['id'], ondelete='SET NULL')
    op.alter_column('empresas', 'moneda_principal',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
    op.create_index(op.f('ix_especialidades_sucursal_id'), 'especialidades', ['sucursal_id'], unique=False)
    op.alter_column('medicos', 'horario_atencion',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicos', 'horario_atencion',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_especialidades_sucursal_id'), table_name='especialidades')
    op.alter_column('empresas', 'moneda_principal',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
    op.drop_constraint('fk_consultas_medicas_cita_id', 'consultas_medicas', type_='foreignkey')
    op.drop_constraint('fk_consultas_medicas_preconsulta_id', 'consultas_medicas', type_='foreignkey')
    op.drop_constraint('fk_consultas_medicas_creado_por', 'consultas_medicas', type_='foreignkey')
    op.drop_index(op.f('ix_consultas_medicas_preconsulta_id'), table_name='consultas_medicas')
    op.drop_index(op.f('ix_consultas_medicas_estado'), table_name='consultas_medicas')
    op.drop_index(op.f('ix_consultas_medicas_creado_por'), table_name='consultas_medicas')
    op.drop_index(op.f('ix_consultas_medicas_codigo'), table_name='consultas_medicas')
    op.drop_index(op.f('ix_consultas_medicas_cita_id'), table_name='consultas_medicas')
    op.create_index(op.f('codigo'), 'consultas_medicas', ['codigo'], unique=True)
    op.alter_column('consultas_medicas', 'reposo_medico',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('consultas_medicas', 'estudios_solicitados',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_constraint('fk_citas_medicas_servicio_id', 'citas_medicas', type_='foreignkey')
    op.drop_index(op.f('ix_citas_medicas_servicio_id'), table_name='citas_medicas')
    op.drop_index(op.f('ix_citas_medicas_estado_pago'), table_name='citas_medicas')
    op.alter_column('citas_medicas', 'recordatorio_enviado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('citas_medicas', 'es_sobreturno',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('citas_medicas', 'estado_pago',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               nullable=True,
               existing_server_default=sa.text("'pendiente'"))

    # ### end Alembic commands ###
